version: '3.8'

services:
  backend:
    build: ./backend
    container_name: trueq-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: trueq-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: trueq-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data:
