"""se agrega a la bd el item valor

Revision ID: 1bbf6a8844a2
Revises: a204ba9f4331
Create Date: 2025-04-14 01:12:04.502330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbf6a8844a2'
down_revision: Union[str, None] = 'a204ba9f4331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('valor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'valor')
    # ### end Alembic commands ###
